apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: attendo-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-pod
          image: ghcr.io/samarthlambture/attendo-backend:c172415ac1c4a67d179b31fcc43ccafb5e31ba81
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secret
