apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: attendo-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-pod
          image: ghcr.io/samarthlambture/attendo-backend:08245ca8d823b02ab46c0f06ecbf84a1be08213f
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secret
