apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: attendo-ns
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: ghcr.io/samarthlambture/attendo-frontend:103e6bd7b23a64bf6797bb7fa0f26344f38e6eff
          ports:
            - containerPort: 80
