apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: attendo-ns
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: ghcr.io/samarthlambture/attendo-frontend:0309fd501037905ee96423b99993e0c9534aee07
          ports:
            - containerPort: 80
