apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: attendo-ns
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: ghcr.io/samarthlambture/attendo-frontend:08245ca8d823b02ab46c0f06ecbf84a1be08213f
          ports:
            - containerPort: 80
